github:
  namespace: "sclorg"
  repos:
    - httpd-container
    - mariadb-container
    - mysql-container
    - nginx-container
    - postgresql-container
    - redis-container
    - s2i-php-container
    - s2i-base-container
    - s2i-python-container
    - s2i-ruby-container
    - s2i-perl-container
    - s2i-nodejs-container
    - valkey-container
  # How many approvals should have PR - default is 2
  approvals: 1
  # How many days, PR should be opened - default is 1 day
  pr_lifetime: 1
  # Labels that blockes merges
  blocker_labels:
    - "pr/failing-ci"
    - "pr/missing-review"
  # Labels that should be present in pull request before merging
  approval_labels:
    - "READY-to-MERGE"
gitlab:
  url: "https://gitlab.com"
  namespace: "redhat/rhel/containers"
  repos:
    - "postgresql-16"
    - "postgresql-15"
    - "postgresql-13"
    - "python-312-minimal"
    - "python-311"
    - "python-312"
    - "valkey-8"
    - "varnish-7"
    - "redis-7"
    - "redis-6"
    - "mariadb-1011"
    - "mariadb-105"
    - "mariadb-103"
    - "mysql-80"
    - "mysql-84"
    - "php-80"
    - "php-81"
    - "php-82"
    - "php-83"
    - "ruby-30"
    - "ruby-31"
    - "ruby-33"
    - "httpd-24"
    - "perl-532"
    - "perl-526"
    - "nodejs-22"
    - "nodejs-24"
    - "nginx-126"
    - "nginx-124"
    - "nginx-122"
    - "nginx-120"
  # Labels that blockes merges
  blocker_labels:
    - "pr/failing-ci"
    - "pr/missing-review"
  # Labels that should be present in pull request before merging
  approval_labels:
    - "READY-to-MERGE"
