on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

name: Run Tox tests on auto-merger

jobs:
  tox_test:
    name: Tox test
    strategy:
      matrix:
        tox_env: [py38, py39, py310, py311, py312]
    # Use GitHub's Linux Docker host
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Tox tests on auto-merger
      id: test
      uses: fedora-python/tox-github-action@main
      with:
        tox_env: ${{ matrix.tox_env }}
        dnf_install: gcc rpm-devel git python3-devel
